[package]
name = "renamer"
version = "0.1.4"
edition = "2021"

[dependencies]
alphanumeric-sort = "1.5.3"
clap = { version = "4.5.20", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["from"] }
regex = "1.11.1"


[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
